name: Run Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # Restart every 6 hours

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        mkdir -p downloads
        python bot.py
